#!/bin/bash

#

# List of servers (replace with IPS or hostname)
servers =("server1 "server2" "server3")

# Remote log file path
remote_log_path = "/var/log/app.log"

# centralized location to store log files
centralized_location = "/path/to/centralized/logs"

# Loop through servers and copy log files
for server in "${servers[@]}" do
	echo "Copying log file from $server..."

	#use scp to copy log file from remote server to centralized location
	scp user@$server:$remote_log_path $centralized_location

	if[ $? -eq 0]; then
		echo "Log file from $server copied successfully."
	else 
		echo "Error copying log file from $server."
	fi
done

echo "Log collection completed."

#Write a script to remotely collect log files from each server and store them in a centralized location.

